version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"

  webserver:
    build:
      context: api/
    image: fastapi_service
    volumes:
      - type: bind
        source: ${MAIN_DIRECTORY_FULL_PATH}/logs/
        target: /app/logs
    
    restart: always
    depends_on:
      - postgres
    ports:
      - "8002:8002"

volumes:   # add this section
  pgdata:    # does not need anything underneath this